//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DısOzellik
    {
        public DısOzellik()
        {
            this.IlanDısOzellik = new HashSet<IlanDısOzellik>();
        }
    
        public int DOID { get; set; }
        public string DısOzellik1 { get; set; }
    
        public virtual ICollection<IlanDısOzellik> IlanDısOzellik { get; set; }
    }
}
