//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanDısOzellik
    {
        public int IDOID { get; set; }
        public int IlanID { get; set; }
        public int DOID { get; set; }
    
        public virtual DısOzellik DısOzellik { get; set; }
        public virtual Ilan Ilan { get; set; }
    }
}
