//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanDetay
    {
        public int IlanDetayID { get; set; }
        public string IdOdaSayisi { get; set; }
        public string IdBinaYasi { get; set; }
        public Nullable<bool> IdEsyaliMi { get; set; }
        public string IdBinaKat { get; set; }
        public string IdBinaKacinciKat { get; set; }
        public Nullable<bool> IdBinaIsitma { get; set; }
        public Nullable<int> IlanID { get; set; }
    
        public virtual Ilan Ilan { get; set; }
    }
}
