//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilan
    {
        public Ilan()
        {
            this.IlanDetay = new HashSet<IlanDetay>();
            this.IlanDısOzellik = new HashSet<IlanDısOzellik>();
            this.IlanIcOzellik = new HashSet<IlanIcOzellik>();
            this.Resim = new HashSet<Resim>();
        }
    
        public int IlanID { get; set; }
        public string IlanBaslik { get; set; }
        public string İlanFiyat { get; set; }
        public Nullable<System.DateTime> IlanTarih { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> IslemID { get; set; }
        public Nullable<int> KimdenID { get; set; }
        public string IlanVResim { get; set; }
        public string IlanAdres { get; set; }
        public string IlanAciklama { get; set; }
        public Nullable<bool> IlanVitrin { get; set; }
    
        public virtual Islem Islem { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Kimden Kimden { get; set; }
        public virtual ICollection<IlanDetay> IlanDetay { get; set; }
        public virtual ICollection<IlanDısOzellik> IlanDısOzellik { get; set; }
        public virtual ICollection<IlanIcOzellik> IlanIcOzellik { get; set; }
        public virtual ICollection<Resim> Resim { get; set; }
    }
}
